import path from 'path';
import fs from 'fs';
import { productCategories, ProductCategory } from '../types';
import { processWithComfyUI, generateTextToImage } from './comfyui';
import { generateImagesExternal, editImageExternal, isImageGenerationModel } from './imageProvider';
import { ProviderConfig } from './llmProvider';
import { sendUpdate } from './websocket';

function normalizeCategory(category: string | undefined): ProductCategory {
  const c = (category || 'diger').toLowerCase();
  return (productCategories.includes(c as ProductCategory) ? c : 'diger') as ProductCategory;
}

function sessionOutputDir(sessionId: string): string {
  const dir = path.resolve('output', sessionId);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Prompt-driven image edit of a single uploaded/existing image. When a provider
 * with an image-capable model is configured (e.g. gpt-image / gemini-2.5-flash-image)
 * the edit is delegated to the external provider; otherwise the ComfyUI
 * product-studio workflow is reused with the seller's instruction injected as
 * the positive prompt (see comfyui.loadWorkflow). Output lands in the session
 * directory so GET /ai/status/:id and /ai/output/:id/:file can serve it.
 */
export async function runImageEdit(opts: {
  imagePath: string;
  prompt: string;
  category?: string;
  sessionId: string;
  provider?: ProviderConfig;
}): Promise<void> {
  const category = normalizeCategory(opts.category);
  const outputDir = sessionOutputDir(opts.sessionId);

  sendUpdate(opts.sessionId, 'editing', 'Görsel AI ile düzenleniyor...');

  let generated: string[];
  const provider = opts.provider;
  if (provider && provider.model && isImageGenerationModel(provider.model)) {
    sendUpdate(opts.sessionId, 'editing', 'Görsel harici AI sağlayıcısıyla düzenleniyor...');
    generated = await editImageExternal(provider, opts.imagePath, opts.prompt, outputDir);
  } else {
    generated = await processWithComfyUI(
      opts.imagePath,
      category,
      (msg) => sendUpdate(opts.sessionId, 'editing', msg),
      { prompt: opts.prompt, outputDir }
    );
  }

  if (generated.length === 0) {
    throw new Error('Görsel düzenleme sonucu üretilemedi (çıktı döndürülmedi).');
  }

  sendUpdate(opts.sessionId, 'completed', 'Görsel düzenlendi', generated);
}

/**
 * Brand-new product images from a text prompt. When a provider with an
 * image-capable model is configured the images are generated by the external
 * provider; otherwise the programmatic ComfyUI text-to-image workflow is used.
 * `count` images in {1..4}, each billed separately by the core API.
 */
export async function runImageGenerate(opts: {
  prompt: string;
  category?: string;
  count: number;
  sessionId: string;
  provider?: ProviderConfig;
}): Promise<void> {
  const category = normalizeCategory(opts.category);
  const outputDir = sessionOutputDir(opts.sessionId);

  sendUpdate(opts.sessionId, 'generating', `Yeni görsel(ler) üretiliyor (${opts.count})...`);

  let generated: string[];
  const provider = opts.provider;
  if (provider && provider.model && isImageGenerationModel(provider.model)) {
    sendUpdate(opts.sessionId, 'generating', `Görseller harici AI sağlayıcısıyla üretiliyor (${opts.count})...`);
    generated = await generateImagesExternal(provider, opts.prompt, opts.count, outputDir);
  } else {
    generated = await generateTextToImage(opts.prompt, category, opts.count, outputDir, (msg) =>
      sendUpdate(opts.sessionId, 'generating', msg)
    );
  }

  if (generated.length === 0) {
    throw new Error('Görsel üretilemedi (çıktı döndürülmedi).');
  }

  sendUpdate(opts.sessionId, 'completed', 'Görseller hazır', generated);
}